<a target="_blank" href="https://colab.research.google.com/github/dnanad/ML-Playground/blob/main/concepts/cross_entropy.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

## PyTorch

1. Binary cross Entropy using Pytorch

In [1]:
import torch
import torch.nn as nn

# PyTorch random to generate the input features(X) and labels(y) values.

X = torch.randn(10)
y = torch.randint(2, (10,), dtype=torch.float)
print(X)
print(y)

tensor([ 0.7855,  0.6441, -2.3788,  0.4390, -0.0964, -0.5358, -0.4945, -0.3326,
         1.6942,  0.4703])
tensor([0., 0., 0., 0., 1., 1., 0., 1., 0., 1.])


In [3]:
# sigmoid function as the activation function of the inputs.
# pass the PyTorch sigmoid module to our input(X) features.

X_continous_values = torch.sigmoid(X)
print(X_continous_values)

tensor([0.8155, 0.6302, 0.8245, 0.6592, 0.5762, 0.6431, 0.5093, 0.4953, 0.4907,
        0.7651])


In [4]:
# Pytorch Binary Cross-Entropy loss:

loss = nn.BCELoss()(X_continous_values, y)
print(loss)

tensor(0.9344)


2. Categorical Cross Entropy using Pytorch

-  categorical Cross-Entropy module, the softmax activation function has already been applied to the formula, so need to use an activation function
- a multi-class problem, the input features have five classes(class_0, class_1, class_2, class_3, class_4)
- input features(X) and labels(y)


In [7]:
X = torch.randn(10, 5)
print(X)

tensor([[ 0.5104,  0.7656, -2.4041,  1.0598, -0.4766],
        [-2.0465,  0.2777,  0.1400, -1.3790, -0.6619],
        [-0.7444,  0.1774, -0.1620, -0.5327, -0.6141],
        [-0.5336,  1.3594,  1.0221, -0.5135,  1.2082],
        [-0.7437,  0.5133,  0.8821, -0.0938,  0.5299],
        [ 0.5208,  2.2355, -0.0859,  1.0182, -0.4713],
        [ 0.7050,  0.5397, -0.2982,  0.6093,  0.7362],
        [ 0.1844,  0.0647, -1.4266,  0.3292,  0.2872],
        [ 0.1275, -1.0810, -1.9952,  1.0795, -0.4866],
        [-0.1119,  0.2798,  0.1231, -0.1325,  0.9417]])


In [8]:
y = torch.randint(5, (10,))
print(y)

tensor([2, 2, 3, 4, 4, 2, 1, 3, 2, 4])


In [9]:
# The multi-class cross-entropy is calculated as follows:

loss = nn.CrossEntropyLoss()(X, y)
print(loss)

tensor(2.0300)


## TensorFlow
1. Binary Cross Entropy:


In [16]:
import tensorflow as tf


actual_values = [0, 1, 0, 0, 0, 0]
predicted_values = [0.5, 0.7, 0.2, 0.3, 0.5, 0.6]

In [14]:
loss = tf.keras.losses.BinaryCrossentropy()(actual_values, predicted_values)
print(loss.numpy)

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=float32, numpy=0.5398464>>


2. Categorical Cross-Entropy

Let’s say we have three classes(cat, dog, bear) to predict. Our actual image/class is a dog; therefore, we have theoretically (0, 1, 0). Where 1 represents the actual image and 0, where the image is not a dog. Our values will be:

In [20]:
actual_values = [0, 1, 0]

# Hypothetically the model predicts that the image is 5% likely to be a cat, 85% a dog, and 10% a bear. Then our predicted values will be:

predicted_values = [0.05, 0.85, 0.10]

actual_values = tf.convert_to_tensor(actual_values)
predicted_values = tf.convert_to_tensor(predicted_values)


loss = tf.keras.losses.CategoricalCrossentropy()
loss = loss(actual_values, predicted_values)
print(loss.numpy)

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=float32, numpy=0.1625189>>
